---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "localinstance"
        instance_type: "t2.micro"
        region: "us-east-1"
        image_id: "ami-0fff1b9a61"  # Replace with your desired AMI
        wait: true
        count: 1
        vpc_subnet_id: "subnet-05864f24efdd82bc6"  # Optional, use if not in default VPC
        security_group:               # Updated to use the correct parameter
          - "localinstance-subnet-private1-us-east-1a"                 # Replace with your security group ID
        tags:                             # Updated tag structure
          Name: "Ansible-EC2"
      register: ec2

    - name: Display instance information
      debug:
        var: ec2

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 10
        timeout: 300
        state: started

    - name: Display public IP of launched instance
      debug:
        msg: "Instance public IP: {{ ec2.instances[0].public_ip_address }}"
