---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws             # Key used for SSH
    region: us-east-1       # Region may affect response and pricing
    image: ami-0fff1b9a61 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "example testing"
    instance_type: t2.nano       # Choose instance type, check AWS for pricing
    # vpc_id: subnet-012345
    sec_group: "test-security-group"

  tasks:
    - name: Provisioning EC2 instances
      block:

      - name: Create security group
        amazon.aws.ec2_security_group:
          name: "{{ sec_group }}"
          description: "Sec group for app"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"  # From vault as defined
          aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
          rules:                                # allows ssh on port 22
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
