---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "localinstance"
        instance_type: "t2.micro"
        region: "us-east-1"
        image_id: "ami-0a676bff45ee7534e"  # Replace with your desired AMI
        wait: true
        count: 1
        vpc_subnet_id: "subnet-0c138a7940b30644c"  
        security_group: essential                 
        tags:                             
          Name: "Ansible-EC222"
      register: ec2

    - name: Display instance information
      debug:
        var: ec2
