---
- name: Run only sudo commands for vgs display
  hosts: all
  tasks:
    - name: display vg deatils
      ansible.builtin.command: sudo vgdisplay
      register: vgdis
      become: true
      become_exe: /usr/local/sudo
      become_flags: "-u admin" 
      
    - name: printing vgdisplay output
      debug:
        var: vgdis
