---
- name: Run only sudo commands for vgs display
  hosts: all
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  become_flag: "-u admin"
  tasks:
    - name: display vg deatils
      ansible.builtin.command: sudo vgdisplay
      register: vgdis
    - name: printing vgdisplay output
      debug:
        var: vgdis
