---
- name: Run only sudo commands for vgs display
  hosts: all
  tasks:
    - name: Rename a VG by name
      community.general.lvg_rename:
       vg: tstvg
       vg_new: mytstvg
      register: vgdis
      become: true
      become_exe: /usr/bin/sudo
      become_flags: "-u admin"
