---
- name: Run only sudo commands for dnf action
  hosts: all
  #gather_facts: no
  become: true
  become_method: sudo
  become_exe: /usr/bin/sudo
  become_flags: "-u admin"
  
  tasks:
    - name: list vgs command
      ansible.builtin.command: vgs
